//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class config_primary_key
    {
        public short prk_id { get; set; }
        public string primary_key_table { get; set; }
        public string primary_key { get; set; }
        public string key_name { get; set; }
        public Nullable<bool> primary_key_status { get; set; }
    }
}
