//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class engage_resume
    {
        public short res_id { get; set; }
        public string human_name { get; set; }
        public string engage_type { get; set; }
        public string human_address { get; set; }
        public string human_postcode { get; set; }
        public string human_major_kind_id { get; set; }
        public string human_major_kind_name { get; set; }
        public string human_major_id { get; set; }
        public string human_major_name { get; set; }
        public string human_telephone { get; set; }
        public string human_homephone { get; set; }
        public string human_mobilephone { get; set; }
        public string human_email { get; set; }
        public string human_hobby { get; set; }
        public string human_specility { get; set; }
        public string human_sex { get; set; }
        public string human_religion { get; set; }
        public string human_party { get; set; }
        public string human_nationality { get; set; }
        public string human_race { get; set; }
        public Nullable<System.DateTime> human_birthday { get; set; }
        public Nullable<short> human_age { get; set; }
        public string human_educated_degree { get; set; }
        public Nullable<short> human_educated_years { get; set; }
        public string human_educated_major { get; set; }
        public string human_college { get; set; }
        public string human_idcard { get; set; }
        public string human_birthplace { get; set; }
        public Nullable<decimal> demand_salary_standard { get; set; }
        public string human_history_records { get; set; }
        public string remark { get; set; }
        public string recomandation { get; set; }
        public string human_picture { get; set; }
        public string attachment_name { get; set; }
        public Nullable<short> check_status { get; set; }
        public string register { get; set; }
        public Nullable<System.DateTime> regist_time { get; set; }
        public string checker { get; set; }
        public Nullable<System.DateTime> check_time { get; set; }
        public Nullable<short> interview_status { get; set; }
        public Nullable<double> total_points { get; set; }
        public Nullable<short> test_amount { get; set; }
        public string test_checker { get; set; }
        public Nullable<System.DateTime> test_check_time { get; set; }
        public string pass_register { get; set; }
        public Nullable<System.DateTime> pass_regist_time { get; set; }
        public string pass_checker { get; set; }
        public Nullable<System.DateTime> pass_check_time { get; set; }
        public Nullable<short> pass_check_status { get; set; }
        public string pass_checkComment { get; set; }
        public string pass_passComment { get; set; }
    }
}
