//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class engage_subjects
    {
        public short sub_id { get; set; }
        public string first_kind_id { get; set; }
        public string first_kind_name { get; set; }
        public string second_kind_id { get; set; }
        public string second_kind_name { get; set; }
        public string register { get; set; }
        public Nullable<System.DateTime> regist_time { get; set; }
        public string derivation { get; set; }
        public string content { get; set; }
        public string key_a { get; set; }
        public string key_b { get; set; }
        public string key_c { get; set; }
        public string key_d { get; set; }
        public string key_e { get; set; }
        public string correct_key { get; set; }
        public string changer { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
    }
}
