//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class engage_answer
    {
        public short ans_id { get; set; }
        public string answer_number { get; set; }
        public string exam_number { get; set; }
        public Nullable<short> resume_id { get; set; }
        public Nullable<short> interview_id { get; set; }
        public string human_name { get; set; }
        public string human_idcard { get; set; }
        public string major_kind_id { get; set; }
        public string major_kind_name { get; set; }
        public string major_id { get; set; }
        public string major_name { get; set; }
        public Nullable<System.DateTime> test_time { get; set; }
        public string use_time { get; set; }
        public Nullable<decimal> total_point { get; set; }
    }
}
