//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary_standard
    {
        public short ssd_id { get; set; }
        public string standard_id { get; set; }
        public string standard_name { get; set; }
        public string designer { get; set; }
        public string register { get; set; }
        public string checker { get; set; }
        public string changer { get; set; }
        public Nullable<System.DateTime> regist_time { get; set; }
        public Nullable<System.DateTime> check_time { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public Nullable<decimal> salary_sum { get; set; }
        public Nullable<short> check_status { get; set; }
        public Nullable<short> change_status { get; set; }
        public string check_comment { get; set; }
        public string remark { get; set; }
    }
}
