//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary_grant_details
    {
        public short grd_id { get; set; }
        public string salary_grant_id { get; set; }
        public string human_id { get; set; }
        public string human_name { get; set; }
        public Nullable<decimal> bouns_sum { get; set; }
        public Nullable<decimal> sale_sum { get; set; }
        public Nullable<decimal> deduct_sum { get; set; }
        public Nullable<decimal> salary_standard_sum { get; set; }
        public Nullable<decimal> salary_paid_sum { get; set; }
    }
}
