//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary_grant
    {
        public short sgr_id { get; set; }
        public string salary_grant_id { get; set; }
        public string salary_standard_id { get; set; }
        public string first_kind_id { get; set; }
        public string first_kind_name { get; set; }
        public string second_kind_id { get; set; }
        public string second_kind_name { get; set; }
        public string third_kind_id { get; set; }
        public string third_kind_name { get; set; }
        public Nullable<short> human_amount { get; set; }
        public Nullable<decimal> salary_standard_sum { get; set; }
        public Nullable<decimal> salary_paid_sum { get; set; }
        public string register { get; set; }
        public Nullable<System.DateTime> regist_time { get; set; }
        public string checker { get; set; }
        public Nullable<System.DateTime> check_time { get; set; }
        public Nullable<short> check_status { get; set; }
    }
}
